export const environment = {
  production: true,
  apiStageEnv: 'prod',
  apiCacheExpiryHours: 12,
  capsuleApiGateway: 'a4dxqq7irh',
  courseApiGateway: 'pir8ksji0b',
  eventApiGateway: 'df12haib2m',
  videoApiGateway: 'kppi2bylsk',
  interviewprepApiGateway: 'oati6nlc07',
  researchPaperApiGateway: 'flve5ir6cc',
  feedbackApiGateway: 'ry63msg3qf',
  subscriptionApiGateway: '3nfpqpcsd0',
  topicApiGateway: '7j4scuzrp9',
  tekByteApiGateway: '8aor8j6icj',
  insightsApiGateway: 'xmq2n39cqe',
  userApiGateway: 'klpgscbxhh',
  marketplaceApiGateway: '2qdikhxbob',
  digestApiGateway: '7vrqxopm10',
  awsRegion: 'us-east-1',
  apiEndpointTemplate: 'https://{{api-gateway}}.execute-api.{{aws-region}}.amazonaws.com/prod',
  awsCognitoConfigs: {
    clientId: '31mi0mrtgief8i94su1ejq1pgg',
    clientSecret: '1tvg13ji1ebc5can275k4tj5i5rhqshevma5cceofaq25atednh0',
    redirectUri: 'https://dev.tekcapzule.com',
    domain: 'https://tekcapzuledev-staging.auth.us-east-1.amazoncognito.com',
  },
};
