export const environment = {
  production: true,
  apiStage: 'dev',
  apiCacheExpiryHours: 12,
  userApiGateway: 'tpuvjtmfy9',
  eventApiGateway: 't9uk11ucqa',
  courseApiGateway: 'pir8ksji0b',
  marketplaceApiGateway: '2qdikhxbob',
  capsuleApiGateway: 'zgzztfoaxe',
  topicApiGateway: 'ydfobf5vfd',
  feedbackApiGateway: '1eynm6e2p8',
  subscriptionApiGateway: 'r8stxkvqs4',
  digestApiGateway: '7vrqxopm10',
  tekByteApiGateway: '8aor8j6icj',
  videoApiGateway: 'kppi2bylsk',
  interviewprepApiGateway: 's19tfj8cee',
  researchPaperApiGateway: 'flve5ir6cc',
  insightsApiGateway: '878m5ejncb',
  campaignApiGateway: 'fbc0hgdw4j',
  awsRegion: 'us-east-1',
  apiEndpointTemplate: 'https://{{api-gateway}}.execute-api.{{aws-region}}.amazonaws.com/dev',
  awsCognitoConfigs: {
    clientId: '31mi0mrtgief8i94su1ejq1pgg',
    clientSecret: '1tvg13ji1ebc5can275k4tj5i5rhqshevma5cceofaq25atednh0',
    redirectUri: 'https://dev.tekcapsule.com',
    domain: 'https://tekcapsuledev-staging.auth.us-east-1.amazoncognito.com',
  },
};
