export const environment = {
  production: true,
  apiStageEnv: 'prod',
  apiCacheExpiryHours: 12,
  capsuleApiGateway: 'a4dxqq7irh',
  courseApiGateway: 'pir8ksji0b',
  eventApiGateway: 'df12haib2m',
  feedbackApiGateway: 'ry63msg3qf',
  subscriptionApiGateway: '3nfpqpcsd0',
  topicApiGateway: '7j4scuzrp9',
  tekByteApiGateway: 'ddrp8i0mtd',
  userApiGateway: 'klpgscbxhh',
  marketplaceApiGateway: '2qdikhxbob',
  digestApiGateway: '7vrqxopm10',
  awsRegion: 'execute-api.us-east-1',
  apiEndpointTemplate: 'https://{{api-gateway}}.{{aws-region}}.amazonaws.com/prod',
};
