export const environment = {
  production: true,
  apiStage: 'dev',
  apiCacheExpiryHours: 12,
  capsuleApiGateway: 'kzqdp4mtmd',
  courseApiGateway: 'pir8ksji0b',
  eventApiGateway: 't9uk11ucqa',
  videoApiGateway: 'kppi2bylsk',
  interviewprepApiGateway: 'oati6nlc07',
  researchPaperApiGateway: 'flve5ir6cc',
  feedbackApiGateway: '7a0ynuuzb7',
  subscriptionApiGateway: 'jianrwq924',
  topicApiGateway: 'ydfobf5vfd',
  tekByteApiGateway: '8aor8j6icj',
  insightsApiGateway: 'xmq2n39cqe',
  marketplaceApiGateway: '2qdikhxbob',
  userApiGateway: 'x5jyub91a3',
  digestApiGateway: '7vrqxopm10',
  awsRegion: 'us-east-1',
  apiEndpointTemplate: 'https://{{api-gateway}}.execute-api.{{aws-region}}.amazonaws.com/dev',
  awsCognitoConfigs: {
    clientId: '31mi0mrtgief8i94su1ejq1pgg',
    clientSecret: '1tvg13ji1ebc5can275k4tj5i5rhqshevma5cceofaq25atednh0',
    redirectUri: 'https://dev.tekcapsule.com',
    domain: 'https://tekcapsuledev-staging.auth.us-east-1.amazoncognito.com',
  },
};
