export const environment = {
  production: true,
  apiStageEnv: 'prod',
  apiCacheExpiryHours: 12,
  capsuleApiGateway: 'a4dxqq7irh',
  courseApiGateway: 'pir8ksji0b',
  eventApiGateway: 'df12haib2m',
  videoApiGateway: 'kppi2bylsk',
  interviewprepApiGateway: 'oati6nlc07',
  researchPaperApiGateway: 'flve5ir6cc',
  feedbackApiGateway: 'ry63msg3qf',
  subscriptionApiGateway: '3nfpqpcsd0',
  topicApiGateway: '7j4scuzrp9',
  tekByteApiGateway: '8aor8j6icj',
  userApiGateway: 'klpgscbxhh',
  marketplaceApiGateway: '2qdikhxbob',
  digestApiGateway: '7vrqxopm10',
  awsRegion: 'execute-api.us-east-1',
  apiEndpointTemplate: 'https://{{api-gateway}}.{{aws-region}}.amazonaws.com/prod',
};
