export const environment = {
  production: true,
  apiStage: 'dev',
  apiCacheExpiryHours: 12,
  capsuleApiGateway: 'kzqdp4mtmd',
  courseApiGateway: 'pir8ksji0b',
  eventApiGateway: 't9uk11ucqa',
  videoApiGateway: 'kppi2bylsk',
  interviewprepApiGateway: 'oati6nlc07',
  researchPaperApiGateway: 'flve5ir6cc',
  feedbackApiGateway: '7a0ynuuzb7',
  subscriptionApiGateway: 'jianrwq924',
  topicApiGateway: 'ydfobf5vfd',
  tekByteApiGateway: '66ja8b3hcl',
  marketplaceApiGateway: '2qdikhxbob',
  userApiGateway: 'x5jyub91a3',
  digestApiGateway: '7vrqxopm10',
  awsRegion: 'execute-api.us-east-1',
  apiEndpointTemplate: 'https://{{api-gateway}}.{{aws-region}}.amazonaws.com/dev',
};
