/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "tekcapsuleweb-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dmiglhq5u9z5m.cloudfront.net",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JOHxTrcti",
    "aws_user_pools_web_client_id": "3alea5j8k2ipvt30506ikdv11u",
    "aws_user_pool_client_secret":"1bg27scb7fpa62giutpsi3e831ge56ih7banelt14i9or8ok53j8",
    "oauth": {
        "domain": "https://tekcapsule.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dmiglhq5u9z5m.cloudfront.net/",
        "redirectSignOut": "https://dmiglhq5u9z5m.cloudfront.net/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_login_mechanism": [
        "EMAIL",
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    }
};


export default awsmobile;
